### ISSUE TITLE
Future work?

### ISSUE THREAD

**Issue by Pat-Lafon** [ngsankha/absynthe#11]
Hello! I found this paper to be very cool now that I'm learning a bit more about Abstract Interpretation in my studies. The paper leaves a few areas for future work like domain specific optimizations and better leveraging the product domain. Is that work that you or your collaborators are currently pursuing? Is there a pre-print in the pipeline for any of the future work?

**Comment by ngsankha** [comment]
Thanks for your interest, Patrick! We are working to apply Absynthe to solve some more domain-specific problem by designing interesting abstractions. However, there is a fundamental tension between the optimizations we can unlock with the Product domain when we go domain specific vs how much of the framework can stay general. We don't have any preprint at the moment. I would be happy to chat more with you if you are interested, and see if we find some common ideas.
